on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/vote-app:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/vote-app:latest .
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/vote-app:${{ github.sha }}
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/vote-app:latest